### ISSUE TITLE
Add `golangci-lint`

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/hotdog#12]
```
I think this is something golangci-lint would catch. 
Might be good to put that on the list to add some day.
```

_Originally posted by @stmcginnis in https://github.com/bottlerocket-os/hotdog/pull/11#pullrequestreview-1242747841_
      
---

Let's add `golangci-lint` as a `make` target and a GitHub action!

**Comment by bcressey** [comment]
Resolving given the planned end-of-life - #12.
